USE DATABASE USER_DB_POODLE;
USE SCHEMA RAW_DATA;

-- 1. Real-Time Weather Table
CREATE TABLE IF NOT EXISTS RAW_WEATHER_REALTIME (
    OBSERVATION_TIME TIMESTAMP_NTZ, 
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    DEW_POINT FLOAT,
    FEELS_LIKE_TEMP FLOAT,
    PRECIPITATION_TOTAL FLOAT,
    RAIN FLOAT,
    CLOUD_COVER FLOAT,
    WIND_SPEED FLOAT,
    WIND_GUSTS FLOAT,
    WIND_DIRECTION FLOAT,
    PRESSURE FLOAT,
    IS_DAY_FLAG INT,
    SOLAR_RADIATION FLOAT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Real-Time Air Quality Table
CREATE TABLE IF NOT EXISTS RAW_AIRQUALITY_REALTIME (
    OBSERVATION_TIME TIMESTAMP_NTZ,
    PM10 FLOAT,
    PM2_5 FLOAT,
    CARBON_MONOXIDE FLOAT,
    NITROGEN_DIOXIDE FLOAT,
    OZONE FLOAT,
    SULPHUR_DIOXIDE FLOAT,
    US_AQI FLOAT,
    UV_INDEX FLOAT,
    DUST FLOAT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT 'Real-Time tables created successfully.' as STATUS;


-- Checking data in RAW_WEATHER_REALTIME
SELECT * FROM USER_DB_POODLE.RAW_DATA.RAW_WEATHER_REALTIME;

-- Checking data in RAW_AIRQUALITY_REALTIME
SELECT * FROM USER_DB_POODLE.RAW_DATA.RAW_AIRQUALITY_REALTIME;