-- 1. SET CONTEXT
USE DATABASE USER_DB_POODLE;

-- 2. CREATE SCHEMAS
-- We create specific schemas to organize your data flow
CREATE SCHEMA IF NOT EXISTS RAW_DATA;  -- API Data lands here
CREATE SCHEMA IF NOT EXISTS STAGING;   -- dbt cleans data here
CREATE SCHEMA IF NOT EXISTS ADHOC;     -- For our experiments

CREATE SCHEMA IF NOT EXISTS ANALYTICS; 

-- 3. DEFINE TABLES (Raw Layer)

-- Switch to RAW_DATA schema to create tables inside it
USE SCHEMA RAW_DATA;

-- Table 1: Weather History (5 Years of Data)
CREATE TABLE IF NOT EXISTS RAW_WEATHER_HISTORY (
    OBSERVATION_TIME TIMESTAMP_NTZ PRIMARY KEY,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    DEW_POINT FLOAT,
    FEELS_LIKE_TEMP FLOAT,
    PRECIPITATION_TOTAL FLOAT,
    RAIN FLOAT,
    CLOUD_COVER FLOAT,
    WIND_SPEED FLOAT,
    WIND_GUSTS FLOAT,
    WIND_DIRECTION FLOAT,
    PRESSURE FLOAT,
    IS_DAY_FLAG INT,
    SOLAR_RADIATION FLOAT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Table 2: Air Quality History (For the second DAG)
CREATE TABLE IF NOT EXISTS RAW_AIRQUALITY_HISTORY (
    OBSERVATION_TIME TIMESTAMP_NTZ PRIMARY KEY,
    PM10 FLOAT,
    PM2_5 FLOAT,
    CARBON_MONOXIDE FLOAT,
    NITROGEN_DIOXIDE FLOAT,
    OZONE FLOAT,
    SULPHUR_DIOXIDE FLOAT,
    US_AQI FLOAT,
    UV_INDEX FLOAT,
    DUST FLOAT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Verification
SELECT 'Setup Complete. Schemas and Tables ready in USER_DB_POODLE.' as STATUS;


-- Checking data in RAW_WEATHER_HISTORY
SELECT * FROM USER_DB_POODLE.RAW_DATA.RAW_WEATHER_HISTORY LIMIT 10;

-- Checking data in RAW_WEATHER_HISTORY
SELECT * FROM USER_DB_POODLE.RAW_DATA.RAW_AIRQUALITY_HISTORY;